name: image_proxy
version: 0.1.0
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  http: ^1.2.1
  path: ^1.9.0
  crypto: ^3.0.3
  mime: ^2.0.0
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
